### ISSUE TITLE
List of API changes for app developers (e.g. files.cat)?

### ISSUE THREAD

**Issue by mitra42** [ipfs/interface-ipfs-core#184]
Is there any documentation with a list of the API changes suitable for app developers. 

For example ...I just got bitten by the change of files.cat just started returning Buffer instead of a Stream. I know the change was announced back in October in https://github.com/ipfs/interface-ipfs-core/pull/162 but that is in development, so its only now with the 0.27 that it bites app developers. 

Is there a full list of API changes from 0.26 to 0.27 so we can check for other issues?

The only other one I know of is that app developers who use WebRTC should switch their config to websockets star. 

Have I missed some list ?

**Comment by diasdavid** [comment]
We've been announcing new releases -- https://github.com/ipfs/js-ipfs/issues/1095 -- through all of our most used channels (IRC, Github, Twitter and Reddit). These announcements serve as a changelog and a feature highlight so that devs know beforehand what to expect on next release and have time to update.

We also invite everyone that is using js-ipfs to tell us how and where so that we can run the tests before any release. If you have a strong test suite and your codebase always passing on master, then you just have to add it to the list -- https://github.com/ipfs/js-ipfs/blob/master/RELEASE.md -- and I'll let you know which tests failed so that you know what you need to pay attention to.

With regards to the files.cat returning a buffer. That was actually one feature request you submitted back at https://github.com/ipfs/interface-ipfs-core/issues/164 and got accepted with https://github.com/ipfs/interface-ipfs-core/pull/162, that PR shows the diff between the old and new API, you can find the changes there.

As for your last question, I believe you didn't miss anything else :)

**Comment by mitra42** [comment]
Hi David  - yes, no issues with having made that request and it being changed, it just that I didn't realize it had changed (even though I made the request - I think partly I missed it because Issue #164 was closed before the fix was actually done). 

#1095 gives a good list of NEW features - which is great, I can add the ones I need incrementally. BUT  can I suggest adding a section on each release that highlights things that have (intentionally) changed, I'm sure it would help app developers find the things that break previously working code. Especially since we can't actually make the change in our code even when the fix is done, only when the release gets pushed.

**Comment by diasdavid** [comment]
> I suggest adding a section on each release that highlights things that have (intentionally) changed

I like that 👍
