### ISSUE TITLE
Add API methods to README

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/interface-ipfs-core#91]
Currently, the README only links to the Files and Object methods. However, there are many more methods, as can be seen in https://github.com/ipfs/interface-ipfs-core/tree/master/API. I think that these should also be in the README. It is confusing, otherwise.

Related: I am searching for `ipfs.add(...)`, and am unable to find it.

**Comment by diasdavid** [comment]
True, we need to link everything that is inside on API.

In another note, we have standardised the API between js-ipfs and js-ipfs-api and with that we favour `ipfs.files.add` usage instead of `ipfs.add`, note that they are exactly the same method, if you look at both implementations, one is an alias of the other.

With this migration (which happened really long time ago), we kept the 'utility' methods that people already used in js-ipfs-api under `ipfs.util`, as you can see here: https://github.com/ipfs/js-ipfs-api#utility-functions, these are specific to js-ipfs-api and the reason why they are not part of the standard interface is because we don't want to bloat the js-ipfs code with filesystem stuff when we can't guarantee it is going to run in the nodejs.

**Comment by diasdavid** [comment]
@RichardLitt wanna help with this one?

**Comment by RichardLitt** [comment]
@diasdavid I don't have the time at the moment.

**Comment by diasdavid** [comment]
what about now, can you take a look into this?

**Comment by diasdavid** [comment]
Done now https://github.com/ipfs/interface-ipfs-core#table-of-contents
